class Team < ActiveRecord::Base

  @TEAM_NAME_TO_ID = { 
  "Cardinals" => 1,
  "Falcons" => 2,
  "Ravens" => 3,
  "Bills" => 4,
  "Panthers" => 5,
  "Bears" => 6,
  "Bengals" => 7,
  "Browns" => 8,
  "Cowboys" => 9,
  "Broncos" => 10,
  "Lions" => 11,
  "Packers" => 12,
  "Texans" => 13,
  "Colts" => 14,
  "Jaguars" => 15,
  "Chiefs" => 16,
  "Dolphins" => 17,
  "Vikings" => 18,
  "Patriots" => 19,
  "Saints" => 20,
  "Giants" => 21,
  "Jets" => 22,
  "Raiders" => 23,
  "Eagles" => 24,
  "Steelers" => 25,
  "Chargers" => 26,
  "Rams" => 27,
  "FortyNiners" => 28,
  "49ers" => 28,
  "Titans" => 29,
  "Buccaneers" => 30,
  "Redskins" => 31,
  "Seahawks" => 32,
  "Hawks" => 33,
  "Celtics" => 34,
  "Bobcats" => 35,
  "Bulls" => 36,
  "Cavaliers" => 37,
  "Mavericks" => 38,
  "Nuggets" => 39,
  "Pistons" => 40,
  "Warriors" => 41,
  "Rockets" => 42,
  "Pacers" => 43,
  "Clippers" => 44,
  "Lakers" => 45,
  "Grizzlies" => 46,
  "Heat" => 47,
  "Bucks" => 48,
  "Timberwolves" => 49,
  "Nets" => 50,
  "Hornets" => 51,
  "Knicks" => 52,
  "Thunder" => 53,
  "Magic" => 54,
  "Sixers" => 55,
  "76ers" => 55,
  "Suns" => 56,
  "Trailblazers" => 57,
  "Kings" => 58,
  "Spurs" => 59,
  "Raptors" => 60,
  "Jazz" => 61,
  "Wizards" => 62 }

  def self.team_name_to_id
    @TEAM_NAME_TO_ID 
  end

end
